#!/usr/bin/env bash
source ./pkg.sh

. ./pkg.sh   # or full path

PKG_INSTALL git wget ripgrep xclip tldr jq python3-pip stow

git clone https://github.com/junegunn/fzf.git $HOME/.local/bin/fzf
$HOME/.local/bin/fzf/install
