#!/usr/bin/env bash

sudo apt -y install git ripgrep xclip tldr jq python3-pip stow

sudo apt install openjdk-11-jdk -y

git clone https://github.com/junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install
