#!/usr/bin/env bash

set -e

# Update packages
yay -Syu --noconfirm

# NetworkManager
yay -S --noconfirm networkmanager network-manager-applet
sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service
systemctl --no-pager --full status NetworkManager.service

# Sunsetr
yay -S sunsetr-bin nwg-displays --noconfirm
