#!usr/bin/env bash

if ! command -v git &> /dev/null; then
    sudo pacman -S install git
fi

if [ ! -d $HOME/personal ]; then
    mkdir $HOME/personal
fi

git clone https://github.com/darrelchang03/dev $HOME/personal/dev

pushd $HOME/personal/dev
./run
popd
